### ISSUE TITLE
Scrolling horizontally + vertically simultaneously

### ISSUE THREAD

**Issue by slawekmikula** [chemtrails/horizontal-scroll#1]
First of all thanks for this extension ! Looking for something like this for a long time.

Issue:
- when (in my example in a grid) I have only horizontal scroll, the extension works flawlessly (small count of records in the grid)
- but when there are many records and the vertical scroll appears the scrolling with e.g. shift is simultaneously scrolling is in both directions (e.g. to the right and to the bottom)

Firefox 120. 

It can be seen on the sampler here (vaadin application): https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features

**Comment by chemtrails** [comment]
Thanks. Addressed in [d92f0af](https://github.com/chemtrails/horizontal-scroll/commit/d92f0af4126070c1f9b28bb645ecbe936f847c57), published in new version (0.0.3).

**Comment by slawekmikula** [comment]
Confirmed. Works correctly. Extremely happy :) Thanks
